import React from "react";
import Head from "next/head";
import Link from "next/link";

type LayoutProps = {
  children: React.ReactNode;
  title: String;
};

export default function Layout({ children, title }: LayoutProps) {
  return (
    <>
      <Head>
        <title>{title ? `${title} - ShopperStop` : "ShopperStop"}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='flex min-h-screen flex-col justify-between'>
        <header className=''>
          <nav className='flex h-12 justify-between shadow-md items-center px-4'>
            <Link href='/' className='text-lg font-bold'>
              ShopperStop
            </Link>
            <div>
              <Link className='p-2' href='/cart'>
                Cart
              </Link>
              <Link className='p-2' href='/login'>
                Login
              </Link>
            </div>
          </nav>
        </header>
        <main className='container m-auto mt-4 px-4'>{children}</main>
        <footer className='flex justify-center items-center h-16 shadow-inner'>
          Copyright © 2022 ShopperStop
        </footer>
      </div>
    </>
  );
}
