import React, { useContext, useState, useEffect } from "react";
import Head from "next/head";
import Link from "next/link";
import { StoreContext } from "../utils/Store";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { useSession, signOut } from "next-auth/react";
import { Menu } from "@headlessui/react";
import Cookies from "js-cookie";

type LayoutProps = {
  children: React.ReactNode;
  title: String;
};

export default function Layout({ children, title }: LayoutProps) {
  const { status, data: session } = useSession();
  const { state, dispatch } = useContext(StoreContext);
  const { cart } = state;
  // const cartItems = cart.cartItems;
  const [cartItemsCount, setCartItemsCount] = useState(0);

  useEffect(() => {
    setCartItemsCount(cart.cartItems.reduce((a, c) => a + c.quantity!, 0));
  }, [cart.cartItems]);

  function logoutHandler(): void {
    Cookies.remove("cart");
    dispatch({ type: "CART_RESET" });
    signOut({ callbackUrl: "/login" });
  }

  return (
    <>
      <Head>
        <title>{title ? `${title} - ShopperStop` : "ShopperStop"}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <ToastContainer position='bottom-center' limit={1} />

      <div className='flex min-h-screen flex-col justify-between'>
        <header className=''>
          <nav className='flex h-12 justify-between shadow-md items-center px-4'>
            <Link href='/' className='text-lg font-bold link'>
              ShopperStop
            </Link>
            <div>
              <Link className='p-2 link' href='/cart'>
                Cart
                {cartItemsCount > 0 && (
                  <span className='ml-1 rounded-full bg-red-600 px-2 py-1 text-sm text-white font-bold'>
                    {cartItemsCount}
                  </span>
                )}
              </Link>
              <Link className='p-2' href=''>
                {status === "loading" ? (
                  "Loading"
                ) : session?.user ? (
                  <Menu as='div' className='relative inline-block'>
                    <Menu.Button className='text-blue-600'>
                      {session.user.name}
                    </Menu.Button>
                    <div>
                      <Menu.Items className='absolute right-0 w-56 origin-top-right bg-white shadow-lg'>
                        <Menu.Item>
                          <Link href={"/profile"} className='dropdown-link'>
                            Profile
                          </Link>
                        </Menu.Item>
                        <Menu.Item>
                          <Link
                            href={"/order-history"}
                            className='dropdown-link'
                          >
                            Order History
                          </Link>
                        </Menu.Item>
                        <Menu.Item>
                          <Link
                            href={"#"}
                            className='dropdown-link'
                            onClick={logoutHandler}
                          >
                            Logout
                          </Link>
                        </Menu.Item>
                      </Menu.Items>
                    </div>
                  </Menu>
                ) : (
                  <Link href='/login' className='link'>
                    Login
                  </Link>
                )}
              </Link>
            </div>
          </nav>
        </header>
        <main className='container m-auto mt-4 px-4'>{children}</main>
        <footer className='flex justify-center items-center h-16 shadow-inner'>
          Copyright © 2022 ShopperStop
        </footer>
      </div>
    </>
  );
}
